services:
  app:
    build: .
    #image: next_retro
    ports:
      - "3000:3000"
    #environment:
    #  - NODE_ENV=development
    #  - DATABASE_URL="postgresql://myuser:mypassword@db:5432/myapp?schema=public"
    env_file:
     - .env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=myapp
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: